#! /bin/sh -x
#ffmpeg -y -i /f2/pub/tmp/House.S07E01.720p.HDTV.X264-DIMENSION.mkv -an -v 1 -threads 0 -vcodec h264 -b 500k -bt 175k -refs 1 -deblockalpha 0 -deblockbeta 0 -partitions parti4x4+partp8x8 -subq 1 -me_range 21 -bf 0 -level 30 -g 300 -keyint_min 30 -sc_threshold 40 -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.7 -qmax 51 -qdiff 4 -i_qfactor 0.71428572 -maxrate 768k -bufsize 2M -cmp 1 -s 320×240 -f mp4 -pass 1 /dev/null

#ffmpeg -i /f2/pub/tmp/House.S07E01.720p.HDTV.X264-DIMENSION.mkv -an -pass 1 -s qvga -vcodec libx264 -vpre slow_firstpass -vpre ipod320 -b 200k -metadata "title=House-S07E01" -threads 0 -f ipod House.S07E01.m4v
#ffmpeg -i /f2/pub/tmp/House.S07E01.720p.HDTV.X264-DIMENSION.mkv -acodec libfaac -ab 128k -pass 2 -s qvga -vcodec libx264 -vpre slow -vpre ipod320 -b 200k -metadata "title=House-S07E01" -threads 0 -f ipod House.S07E01.m4v


#ffmpeg -i INPUT -acodec libfaac -ab 128k -s WIDTHxHEIGHT -vcodec libx264 -vpre slow -vpre ipod320 -b BIT_RATE -metdata "title=SOME_TITLE" -threads 0 -f ipod OUTPUT.mp4

#ffmpeg -i INPUT -an -pass 1 -s WIDTHxHEIGHT -vcodec libx264 -vpre slow_firstpass -vpre ipod320 -b BIT_RATE -metadata "title=SOME_TITLE" -threads 0 -f ipod OUTPUT.mp4
#ffmpeg -i INPUT -acodec libfaac -ab 128k -pass 2 -s WIDTHxHEIGHT -vcodec libx264 -vpre slow -vpre ipod320 -b BIT_RATE -metadata "title=SOME_TITLE" -threads 0 -f ipod OUTPUT.mp4

#-metadata "show=How i met your mother" \
#-metadata "tvsn=5" \
#-metadata "tvep=12" \
#
#
##ffmpeg -i INPUT-acodec aac -ac 2 -ab 160k -s 640x480 -vcodec libx264 -vpre slow -vpre iPod640 -b 1200k -f mp4 -threads 0 OUTPUT


ffmpeg \
-i $1 \
-an \
-pass 1 \
-s vga \
-vcodec libx264 \
-vpre ipod640 \
-b 1024k \
-metadata "title=$2" \
-threads 2 \
-f ipod \
$2-pass1 || exit 1

#-vpre slow_firstpass \

ffmpeg \
-i $1 \
-acodec libfaac \
-ab 160k \
-ac 2 \
-pass 2 \
-s vga \
-vcodec libx264 \
-vpre ipod640 \
-b 1200k \
-metadata "title=$2" \
-threads 2 \
-f ipod \
$2 || exit 2

#-vpre slow \

rm x264_2pass.log* $2-pass1

chmod -w $2
