#!/usr/bin/env python

import sys
import random

data=list(sys.stdin)
random.shuffle(data)
filter(sys.stdout.write,data)

#sortdata=[]
#randdata=[]
#
#for rad in sys.stdin:
#	sortdata.append(rad)
#
#while len(sortdata) is not 0:
#	rand=random.randint(0,len(sortdata)-1)
#	randdata.append(sortdata[rand])
#	sortdata.__delitem__(rand)
#
#for rad in randdata:
#	print rad,
