#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
	sys.stderr.write("Usage: %s row1,row2..." % sys.argv[0])
	exit(1)

rows=sys.argv[1].split(",")
data={}
radn=1

for rad in sys.stdin:
	if str(radn) in rows:
		data[str(radn)]=rad
	radn+=1

for rad_index in rows:
	sys.stdout.write(data[rad_index])
